### ISSUE TITLE
Drawing texture

### ISSUE THREAD

**Issue by 53n21e** [jbrd/bevy_mod_imgui#33]
I've been working with bevy_mod_imgui and I'm trying to draw an Image from a Bevy texture using imgui. However, I haven't been able to find a way to access or pass Bevy textures to imgui for rendering. Is there a supported method to achieve this that I might be overlooking?

**Comment by jbrd** [comment]
I don't believe that is possible at the moment but is a reasonable request. I'll look into this once Bevy 0.14 support is finished

**Comment by jbrd** [comment]
So I'm working on this at the moment - a quick and dirty prototype suggests this should be doable...

**Comment by kalucky0** [comment]
Hello. Is there any progress on this feature? Rendering textures using imgui would be immensely useful for me.

**Comment by jbrd** [comment]
Hi, yes, there has been some progress. It has been slow due to other projects / life events taking priority. Will push up a branch in the next couple of days so you can try it out

**Comment by kalucky0** [comment]
Ok, thanks

**Comment by jbrd** [comment]
Okay, I've pushed up a candidate set of changes for custom texture support on the custom-texture branch. This adds two new examples - one that displays a Bevy Image loaded from an asset in an ImGui window, and another that displays a scene rendered to a texture in an ImGui window. If you could give this a try, and let me know how it goes, that'd allow me to close out any remaining issues before merging and releasing this...

**Comment by jbrd** [comment]
**New custom-texture example**

<img width="956" alt="image" src="https://github.com/user-attachments/assets/aef3cc08-9d1e-48e6-915f-8cfacf02deb7">

**New render-to-texture example**

<img width="953" alt="image" src="https://github.com/user-attachments/assets/033293c6-c8f7-4ae7-be64-b26af8d2f5ae">
